apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scriptorium

commonLabels:
  app.kubernetes.io/part-of: scriptorium

resources:
  - namespace.yaml
  - config.yaml
  - networkpolicy.yaml
  - app-bff.yaml
  - app-frontend.yaml
  - app-ingestion.yaml
  - app-agent.yaml
  - app-retrieval.yaml
  - data-stores.yaml
